datasource:
  driverName: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/project_pizza"
  login: postgres
  password: root
  initialSize: 10
  maxActive: 7
jwttoken:
  secret: secretBod
  expire: 2140000000