spring:
  datasource:
    username: postgres
    password: root
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/db/migrations
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: "jdbc:postgresql://localhost:5432/project_pizza"
    user: postgres
    password: root
datasource:
  driverName: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/project_pizza"
  login: postgres
  password: root
  initialSize: 10
  maxActive: 7
jwttoken:
  secret: secretBod
  expire: 2140000000