package com.htp.enums;

public enum Ingredients {

    CHEESE_FETA, DOR_BLU, PARMESAN,
    MOZZARELLA, PEPPERONI, SAUSAGES,
    BACON, BEEF, CHICKEN, SHRIMP,
    SALAMI, MUSHROOMS, PEPPER,
    PINEAPPLE, TOMATOES, OILS, CUCUMBERS
}
